import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: <Icon.Home size={20} />,
    general: true,
    navLink: "/",
    badge: "warning",
  },
  {
    id: "enquiry",
    title: "Enquiry",
    type: "item",
    icon: <Icon.PhoneCall size={20} />,
    permission: "enquiry",
    navLink: "/enquiry",
    badge: "warning",
  },
  {
    id: "sales",
    title: "Sales",
    type: "item",
    icon: <Icon.Target size={20} />,
    permission: "sales_lead",
    navLink: "/sales",
    badge: "warning",
  },
  {
    id: "receipt",
    title: "Receipt",
    type: "item",
    icon: <Icon.Paperclip size={20} />,
    permission: "receipt",
    navLink: "/receipt",
    badge: "warning",
  },
  {
    id: "user",
    title: "Users",
    type: "item",
    icon: <Icon.Users size={20} />,
    navLink: "/users",
    badge: "warning",
  },
  {
    id: "roles",
    title: "Roles",
    type: "item",
    icon: <Icon.Key size={20} />,
    navLink: "/roles",
    badge: "warning",
  },
  {
    id: "products",
    title: "Products",
    type: "item",
    icon: <Icon.Box size={20} />,
    navLink: "/products",
    badge: "warning",
  },
  {
    id: "attributes",
    title: "Attribute Cataloge",
    type: "collapse",
    icon: <Icon.Sliders size={20} />,
    children: [
      {
        id: "categories",
        title: "Categories",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/categories",
      },
      {
        id: "subcategories",
        title: "Subcategories",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/subcategories",
      },
      {
        id: "color",
        title: "Color Varients",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/colors",
      },
      {
        id: "insurance",
        title: "Insurance",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/insurance",
      },
      {
        id: "finance",
        title: "Finance",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/finance",
      },
      {
        id: "department",
        title: "Departments",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/department",
      },
      {
        id: "varient",
        title: "Varients",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/varients",
      },
      {
        id: "payment_types",
        title: "Payment Types",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/payment-types",
      },
      {
        id: "enquiry_types",
        title: "Enquiry Types",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/enquiry-types",
      },
      {
        id: "lead_types",
        title: "Lead Types",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/lead-types",
      },
      {
        id: "lead_categories",
        title: "Lead Categories",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/lead-categories",
      },
      {
        id: "accessories",
        title: "Accessories",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/accessories",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Modules",
  // },
  // {
  //   id: "user",
  //   title: "User",
  //   type: "item",
  //   icon: <Icon.User size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/user",
  // },
  // {
  //   id: "calendar",
  //   title: "Calendar",
  //   type: "item",
  //   icon: <Icon.Calendar size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/calendar",
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "ACCOUNT",
  // },
  // {
  //   id: "profile",
  //   title: "Profile",
  //   type: "item",
  //   icon: <Icon.User size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/pages/profile",
  //   collapsed: true,
  // },
  // {
  //   id: "accountSettings",
  //   title: "Account Settings",
  //   type: "item",
  //   icon: <Icon.Settings size={20} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/pages/account-settings",
  // },
  // {
  //   id: "authentication",
  //   title: "Authentication",
  //   type: "collapse",
  //   icon: <Icon.Unlock size={20} />,
  //   children: [
  //     {
  //       id: "login",
  //       title: "Login",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/pages/login",
  //       newTab: true,
  //     },
  //     {
  //       id: "register",
  //       title: "Register",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/pages/register",
  //       newTab: true,
  //     },
  //     {
  //       id: "forgotPassword",
  //       title: "Forgot Password",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/pages/forgot-password",
  //       newTab: true,
  //     },
  //     {
  //       id: "resetPassword",
  //       title: "Reset Password",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/pages/reset-password",
  //       newTab: true,
  //     },
  //     {
  //       id: "lockScreen",
  //       title: "Lock Screen",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/pages/lock-screen",
  //       newTab: true,
  //     },
  //   ],
  // },
];

export default navigationConfig;
